#!/usr/bin/env python3
"""
Comm Chirp Generator
====================
An original sci-fi communicator sound designer.
Uses FM synthesis to create chirps distinct from any copyrighted sounds.

Requirements:
    pip install numpy pydub

For MP3 export, also install ffmpeg:
    Windows:  https://ffmpeg.org/download.html  (add to PATH)
    Mac:      brew install ffmpeg
    Linux:    sudo apt install ffmpeg

Optional richer playback:
    pip install simpleaudio
"""

import tkinter as tk
from tkinter import ttk, filedialog, messagebox
import numpy as np
import wave
import os
import threading
import tempfile

try:
    from pydub import AudioSegment
    HAS_PYDUB = True
except ImportError:
    HAS_PYDUB = False

try:
    import simpleaudio as sa
    HAS_SIMPLEAUDIO = True
except ImportError:
    HAS_SIMPLEAUDIO = False


SAMPLE_RATE = 44100
TIMELINE_S  = 1.5
MAX_OFF_S   = 1.2


# ═══════════════════════════════════════════════════════════════════════════════
#  Synthesis
# ═══════════════════════════════════════════════════════════════════════════════

def make_envelope(n, attack, release):
    env = np.ones(n)
    atk = min(int(attack * SAMPLE_RATE), max(1, int(n * 0.3)))
    rel = min(int(release * SAMPLE_RATE), max(1, int(n * 0.6)))
    if atk > 0: env[:atk]     = np.linspace(0, 1, atk)
    if rel > 0: env[n - rel:] = np.linspace(1, 0, rel)
    return env


def synth_segment(n, start_freq, end_freq, fm_amount, fm_ratio,
                  brightness, attack, release, volume):
    t       = np.arange(n) / SAMPLE_RATE
    mod     = fm_amount * np.sin(2 * np.pi * start_freq * fm_ratio * t)
    sweep   = np.linspace(start_freq, end_freq, n)
    inst    = np.maximum(sweep + mod, 20)
    phase   = 2 * np.pi * np.cumsum(inst) / SAMPLE_RATE
    carrier = np.sin(phase)
    if brightness > 0.05:
        p2      = 2 * np.pi * np.cumsum(inst * 2) / SAMPLE_RATE
        carrier = carrier * (1 - brightness * 0.4) + np.sin(p2) * brightness * 0.4
    return carrier * make_envelope(n, attack, release) * volume


def build_default_segments(style, duration):
    if style == "double":
        return [(0.0, duration * 0.55), (duration * 0.65, duration * 0.35)]
    elif style == "trill":
        gap = duration * 0.05; sd = (duration - gap * 2) / 3
        return [(0.0, sd), (sd + gap, sd), (2 * sd + 2 * gap, sd)]
    else:
        return [(0.0, duration)]


def n_blips_for_style(style):
    return {"double": 2, "trill": 3}.get(style, 1)


# ═══════════════════════════════════════════════════════════════════════════════
#  Audio I/O
# ═══════════════════════════════════════════════════════════════════════════════

def audio_to_int16(a):
    return (np.clip(a, -1, 1) * 32767).astype(np.int16)

def save_wav(path, audio):
    with wave.open(path, "w") as wf:
        wf.setnchannels(1); wf.setsampwidth(2); wf.setframerate(SAMPLE_RATE)
        wf.writeframes(audio_to_int16(audio).tobytes())

def save_mp3(path, audio):
    if not HAS_PYDUB:
        raise RuntimeError("pydub not installed — run: pip install pydub")
    tmp = tempfile.mktemp(suffix=".wav")
    save_wav(tmp, audio)
    AudioSegment.from_wav(tmp).export(path, format="mp3", bitrate="192k")
    os.remove(tmp)

def save_arduino_h(path, audio, sample_rate=SAMPLE_RATE, var_name="chirp"):
    """
    Export audio as a C header file for use with Arduino / ESP32.

    Usage in your sketch:
        #include "comm_chirp.h"
        // play with ESP32 DAC, I2S, or PWM using CHIRP_DATA / CHIRP_SAMPLES
    """
    # Resample to 8-bit unsigned (0-255) — DAC-friendly for ESP32
    normalised = np.clip(audio, -1.0, 1.0)
    samples_u8 = ((normalised + 1.0) * 127.5).astype(np.uint8)
    n = len(samples_u8)

    guard = var_name.upper() + "_H"
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "// Auto-generated by Comm Chirp Generator",
        f"// {n} samples @ {sample_rate} Hz  ({n/sample_rate*1000:.1f} ms)",
        "// Format: 8-bit unsigned PCM (0-255, centre = 128)",
        "// ESP32 example:",
        "//   dacWrite(DAC1, pgm_read_byte(&CHIRP_DATA[i]));",
        "",
        f"#define CHIRP_SAMPLE_RATE {sample_rate}",
        f"#define CHIRP_SAMPLES      {n}",
        "",
        f"const uint8_t {var_name.upper()}_DATA[] PROGMEM = {{",
    ]

    # Write 16 bytes per line for readability
    for i in range(0, n, 16):
        chunk = samples_u8[i:i+16]
        row   = ", ".join(f"0x{b:02X}" for b in chunk)
        comma = "," if i + 16 < n else ""
        lines.append(f"  {row}{comma}")

    lines += ["};", "", f"#endif // {guard}", ""]

    with open(path, "w") as f:
        f.write("\n".join(lines))


def play_audio(audio):
    if HAS_SIMPLEAUDIO:
        sa.play_buffer(audio_to_int16(audio).tobytes(), 1, 2, SAMPLE_RATE)
        return
    tmp = tempfile.mktemp(suffix=".wav")
    save_wav(tmp, audio)
    import subprocess, sys
    if   sys.platform == "darwin":         subprocess.Popen(["afplay", tmp])
    elif sys.platform.startswith("linux"): subprocess.Popen(["aplay",  tmp])
    elif sys.platform == "win32":
        import winsound
        winsound.PlaySound(tmp, winsound.SND_FILENAME | winsound.SND_ASYNC)


# ═══════════════════════════════════════════════════════════════════════════════
#  Colours
# ═══════════════════════════════════════════════════════════════════════════════

DARK_BG    = "#1a1a2a"
PANEL_BG   = "#252538"
TROUGH_BG  = "#0e0e1c"
HANDLE_COL = "#ffffff"
HANDLE_ACT = "#d0d8ff"
ACCENT     = "#89b4fa"
DARK_FG    = "#ffffff"
MUTED      = "#7878a0"
HINT_FG    = "#5a5a80"       # subtle hint text under slider labels
BTN_BG     = "#2e2e48"
BTN_ACTIVE = "#3e3e5e"
GREEN      = "#a6e3a1"
WAVE_BG    = "#0e0e1c"

MARKER_COLS = ["#f38ba8", "#a6e3a1", "#fab387"]

STYLES = [
    ("Rising sweep",  "rise"),
    ("Falling sweep", "fall"),
    ("Double tap",    "double"),
    ("Trill",         "trill"),
    ("Single blip",   "blip"),
]


# ═══════════════════════════════════════════════════════════════════════════════
#  Slider — round white handle
# ═══════════════════════════════════════════════════════════════════════════════

class Slider(tk.Canvas):
    H = 26; TRACK_H = 4; R = 9

    def __init__(self, parent, from_, to, value, resolution=1,
                 on_change=None, bg=None, **kw):
        _bg = bg or PANEL_BG
        super().__init__(parent, height=self.H, bg=_bg,
                         highlightthickness=0, cursor="hand2", **kw)
        self._from = from_; self._to = to; self._res = resolution
        self._val  = self._snap(float(value))
        self.on_change = on_change
        self._hover = self._dragging = False
        self.bind("<Configure>",       self._redraw)
        self.bind("<ButtonPress-1>",   self._press)
        self.bind("<B1-Motion>",       self._drag)
        self.bind("<ButtonRelease-1>", self._release)
        self.bind("<Enter>",           lambda e: self._seth(True))
        self.bind("<Leave>",           lambda e: self._seth(False))

    def _snap(self, v):
        v = max(self._from, min(self._to, v))
        return round(v / self._res) * self._res if self._res else v

    def _xfor(self, v):
        w = self.winfo_width() or 200; pad = self.R + 2
        return pad + (v - self._from) / max(self._to - self._from, 1e-9) * (w - 2*pad)

    def _vfor(self, x):
        w = self.winfo_width() or 200; pad = self.R + 2
        return self._snap(self._from + (x - pad) / max(w - 2*pad, 1) * (self._to - self._from))

    def _redraw(self, *_):
        self.delete("all")
        w = self.winfo_width() or 200; cy = self.H // 2; pad = self.R + 2
        hx = self._xfor(self._val)
        self.create_rectangle(pad, cy-self.TRACK_H//2, w-pad, cy+self.TRACK_H//2,
                               fill=TROUGH_BG, outline="")
        self.create_rectangle(pad, cy-self.TRACK_H//2, hx, cy+self.TRACK_H//2,
                               fill=ACCENT, outline="")
        col = HANDLE_ACT if (self._hover or self._dragging) else HANDLE_COL
        self.create_oval(hx-self.R, cy-self.R, hx+self.R, cy+self.R,
                         fill=col, outline="#8899cc", width=1)

    def _press(self, e):   self._dragging = True;  self._upd(e.x)
    def _drag(self, e):    self._upd(e.x)
    def _release(self, e): self._dragging = False; self._redraw()
    def _seth(self, v):    self._hover = v;        self._redraw()

    def _upd(self, x):
        nv = self._vfor(x)
        if nv != self._val:
            self._val = nv; self._redraw()
            if self.on_change: self.on_change(nv)

    def get(self): return self._val
    def set(self, v):
        self._val = self._snap(float(v)); self._redraw()
        if self.on_change: self.on_change(self._val)


# ═══════════════════════════════════════════════════════════════════════════════
#  SliderRow — label + hint + slider + live value
# ═══════════════════════════════════════════════════════════════════════════════

class SliderRow(tk.Frame):
    """
    A slider with:
      • a bold label on the left
      • a small italic hint line below the label
      • the slider bar filling available space
      • a live numeric readout on the right
    """
    def __init__(self, parent, label, hint, from_, to, default,
                 resolution=1, unit="", fmt="{:.0f}",
                 on_change=None, label_fg=None, bg=None, **kw):
        _bg = bg or PANEL_BG
        super().__init__(parent, bg=_bg, **kw)
        self._fmt_s = fmt; self._unit = unit; self._cb = on_change
        fg = label_fg or DARK_FG

        # Left column: label + hint stacked — sized by content, not clipped
        left = tk.Frame(self, bg=_bg)
        left.pack(side="left", fill="y", padx=(0, 4))
        tk.Label(left, text=label, bg=_bg, fg=fg,
                 font=("Helvetica", 11), anchor="w").pack(fill="x")
        tk.Label(left, text=hint, bg=_bg, fg=HINT_FG,
                 font=("Helvetica", 9), anchor="w", wraplength=148,
                 justify="left").pack(fill="x", pady=(0, 2))

        # Right: live value readout
        self._lbl = tk.Label(self, text=self._fv(default), bg=_bg, fg=fg,
                             font=("Helvetica", 11, "bold"), width=9, anchor="e")
        self._lbl.pack(side="right")

        # Slider fills the middle
        self.slider = Slider(self, from_=from_, to=to, value=default,
                             resolution=resolution, on_change=self._chg, bg=_bg)
        self.slider.pack(side="left", fill="x", expand=True, padx=(6, 6))

    def _fv(self, v):   return self._fmt_s.format(v) + self._unit
    def _chg(self, v):
        self._lbl.config(text=self._fv(v))
        if self._cb: self._cb(v)
    def get(self):      return self.slider.get()
    def set(self, v):
        self.slider.set(v)
        self._lbl.config(text=self._fv(v))


# ═══════════════════════════════════════════════════════════════════════════════
#  BlipFreqPanel — per-blip start/end frequency controls
# ═══════════════════════════════════════════════════════════════════════════════

class BlipFreqPanel(tk.Frame):
    _DEFAULTS = [(900, 1400), (900, 1400), (900, 1400)]

    def __init__(self, parent, on_change=None, **kw):
        super().__init__(parent, bg=PANEL_BG, **kw)
        self._on_change = on_change
        self._rows      = []   # [(container, start_SliderRow, end_SliderRow)]

    def rebuild(self, n_blips, preserve=True):
        old = [(r[2].get(), r[3].get()) for r in self._rows]
        # destroy every widget we own (border frame + content frame)
        for r in self._rows:
            r[0].destroy()   # border strip
            r[1].destroy()   # content frame
        self._rows = []

        for i in range(n_blips):
            col  = MARKER_COLS[i % len(MARKER_COLS)]
            bg   = self._tint(col)
            name = f"Blip {i+1}" if n_blips > 1 else "Blip"

            border = tk.Frame(self, bg=col, height=2)
            border.pack(fill="x", padx=2, pady=(8 if i > 0 else 2, 0))

            frm = tk.Frame(self, bg=bg)
            frm.pack(fill="x")

            tk.Label(frm, text=name.upper(), bg=bg, fg=col,
                     font=("Helvetica", 9, "bold"), anchor="w"
                     ).pack(fill="x", padx=10, pady=(5, 0))

            sv, ev = (old[i] if preserve and i < len(old)
                      else self._DEFAULTS[i % len(self._DEFAULTS)])

            sr = SliderRow(frm, "Start freq",
                           "pitch the blip begins at",
                           200, 3000, sv, 10, " Hz", "{:.0f}",
                           on_change=lambda _: self._fire(), label_fg=col, bg=bg)
            sr.pack(fill="x", padx=8, pady=3)

            er = SliderRow(frm, "End freq",
                           "pitch the blip lands on",
                           200, 3000, ev, 10, " Hz", "{:.0f}",
                           on_change=lambda _: self._fire(), label_fg=col, bg=bg)
            er.pack(fill="x", padx=8, pady=(0, 7))

            # store border AND content frame so both get destroyed next rebuild
            self._rows.append((border, frm, sr, er))

    def _fire(self):
        if self._on_change: self._on_change()

    def get_freqs(self):
        return [(r[2].get(), r[3].get()) for r in self._rows]

    def set_freqs(self, freq_list):
        for i, (s, e) in enumerate(freq_list):
            if i < len(self._rows):
                self._rows[i][2].set(s); self._rows[i][3].set(e)

    @staticmethod
    def _tint(c):
        return (f"#{int(c[1:3],16)//8:02x}"
                f"{int(c[3:5],16)//8:02x}"
                f"{int(c[5:7],16)//8:02x}")


# ═══════════════════════════════════════════════════════════════════════════════
#  WaveCanvas — draggable per-blip timeline
# ═══════════════════════════════════════════════════════════════════════════════

class WaveCanvas(tk.Canvas):
    HEIGHT = 110; HW = 7

    def __init__(self, parent, on_change=None, **kw):
        super().__init__(parent, bg=WAVE_BG, highlightthickness=0,
                         height=self.HEIGHT, **kw)
        self._segs = []; self._audio = []; self._on_change = on_change
        self._di = self._dx0 = self._ds0 = None
        self.bind("<Configure>",       lambda e: self._draw())
        self.bind("<ButtonPress-1>",   self._press)
        self.bind("<B1-Motion>",       self._move)
        self.bind("<ButtonRelease-1>", self._release)

    def set_segments(self, segs, audio):
        self._segs  = [[s, d] for s, d in segs]
        self._audio = list(audio)
        self._draw()

    def get_start_times(self):
        return [s for s, _ in self._segs]

    def get_mixed_audio(self):
        if not self._segs: return np.zeros(int(0.5 * SAMPLE_RATE))
        total = int((max(s+d for s,d in self._segs) + 0.12) * SAMPLE_RATE)
        out   = np.zeros(total)
        for (s, _), seg in zip(self._segs, self._audio):
            idx = int(s * SAMPLE_RATE); end = min(idx + len(seg), total)
            out[idx:end] += seg[:end - idx]
        out = np.tanh(out * 1.2) / 1.2
        pk  = np.max(np.abs(out))
        if pk > 0: out /= pk / 0.92
        return out

    def _mx(self, i):
        return int(self._segs[i][0] / TIMELINE_S * (self.winfo_width() or 400))

    def _hit(self, x, y):
        for i in range(len(self._segs)):
            mx = self._mx(i)
            if abs(x - mx) <= self.HW and y >= self.HEIGHT - 20: return i
            if abs(x - mx) <= 5: return i
        return None

    def _press(self, e):
        i = self._hit(e.x, e.y)
        if i is not None:
            self._di = i; self._dx0 = e.x; self._ds0 = self._segs[i][0]
            self.config(cursor="sb_h_double_arrow")

    def _move(self, e):
        if self._di is None: return
        w = self.winfo_width() or 400
        self._segs[self._di][0] = max(0.0, min(MAX_OFF_S,
            self._ds0 + (e.x - self._dx0) / w * TIMELINE_S))
        self._draw()

    def _release(self, e):
        if self._di is not None:
            self._di = None; self.config(cursor="")
            if self._on_change: self._on_change()

    def _draw(self):
        self.delete("all")
        w = self.winfo_width() or 400; h = self.HEIGHT; mid = (h-22)//2+4

        for i in range(int(TIMELINE_S*10)+1):
            ts=i*0.1; x=int(ts/TIMELINE_S*w); major=i%5==0
            self.create_line(x, 0, x, h-20, fill="#1c1c32" if major else "#161626")
            if major:
                self.create_text(x+2, 2, text=f"{ts:.1f}s", anchor="nw",
                                 fill=MUTED, font=("Helvetica", 8))
        self.create_line(0, mid, w, mid, fill="#252545")

        if not self._segs:
            self.create_text(w//2, mid, text="adjust parameters to preview",
                             fill=MUTED, font=("Helvetica", 10)); return

        wh = mid - 10
        for i, ((s, d), seg) in enumerate(zip(self._segs, self._audio)):
            if not len(seg): continue
            col = MARKER_COLS[i % len(MARKER_COLS)]
            x0  = int(s/TIMELINE_S*w); x1 = int((s+d)/TIMELINE_S*w)
            sw  = max(x1-x0, 2)
            self.create_rectangle(x0, mid-wh, x1, mid+wh, fill=self._dk(col), outline="")
            step = max(1, len(seg)//(max(sw*2, 1))); pts = seg[::step]; np_ = len(pts)
            coords = []
            for j, v in enumerate(pts):
                coords.extend([x0+j*sw/max(np_-1, 1), mid-v*(wh-2)])
            if len(coords) >= 4:
                self.create_line(*coords, fill=col, width=1.5, smooth=True)

        for i, (s, d) in enumerate(self._segs):
            col = MARKER_COLS[i % len(MARKER_COLS)]; mx = self._mx(i)
            self.create_line(mx, 0, mx, h-20, fill=col, width=1, dash=(3,3))
            by = h-2
            self.create_polygon(mx-7, by, mx+7, by, mx, by-14,
                                 fill=col, outline=WAVE_BG, width=1)
            lx = mx+9 if mx < w-55 else mx-9
            self.create_text(lx, h-18, text=f"{s*1000:.0f} ms",
                             anchor="nw" if mx < w-55 else "ne",
                             fill=col, font=("Helvetica", 8, "bold"))

    @staticmethod
    def _dk(c):
        return (f"#{int(c[1:3],16)//7:02x}"
                f"{int(c[3:5],16)//7:02x}"
                f"{int(c[5:7],16)//7:02x}")


# ═══════════════════════════════════════════════════════════════════════════════
#  ScrollableFrame
# ═══════════════════════════════════════════════════════════════════════════════

class ScrollableFrame(tk.Frame):
    """Vertically scrollable container — place widgets in self.inner."""
    def __init__(self, parent, **kw):
        super().__init__(parent, **kw)
        self._cv = tk.Canvas(self, bg=DARK_BG, highlightthickness=0, borderwidth=0)
        vsb = ttk.Scrollbar(self, orient="vertical", command=self._cv.yview)
        self._cv.configure(yscrollcommand=vsb.set)
        vsb.pack(side="right", fill="y")
        self._cv.pack(side="left", fill="both", expand=True)
        self.inner = tk.Frame(self._cv, bg=DARK_BG)
        self._win  = self._cv.create_window((0, 0), window=self.inner, anchor="nw")
        self.inner.bind("<Configure>", lambda e:
            self._cv.configure(scrollregion=self._cv.bbox("all")))
        self._cv.bind("<Configure>", lambda e:
            self._cv.itemconfig(self._win, width=e.width))
        for seq in ("<MouseWheel>", "<Button-4>", "<Button-5>"):
            self._cv.bind_all(seq, self._wheel)

    def _wheel(self, e):
        if   e.num == 4: self._cv.yview_scroll(-1, "units")
        elif e.num == 5: self._cv.yview_scroll( 1, "units")
        else:            self._cv.yview_scroll(int(-e.delta / 120), "units")


# ═══════════════════════════════════════════════════════════════════════════════
#  Main application
# ═══════════════════════════════════════════════════════════════════════════════

class ChirpApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Comm Chirp Generator")
        self.configure(bg=DARK_BG)
        self.resizable(True, True)
        self.geometry("600x720")
        self._current_audio = None
        self._build_ui()
        self.after(120, lambda: self._generate(reset_positions=True))

    # ── helpers ───────────────────────────────────────────────────────────────

    def _section(self, parent, title):
        """Section header + inner panel frame, packed into parent."""
        outer = tk.Frame(parent, bg=DARK_BG)
        outer.pack(fill="x", padx=16, pady=(10, 0))
        tk.Label(outer, text=title.upper(), bg=DARK_BG, fg=MUTED,
                 font=("Helvetica", 9, "bold"), anchor="w").pack(fill="x", pady=(0, 4))
        inner = tk.Frame(outer, bg=PANEL_BG)
        inner.pack(fill="x")
        return inner

    def _mkslider(self, parent, label, hint, lo, hi, default, res, unit, fmt):
        row = SliderRow(parent, label, hint, lo, hi, default, res, unit, fmt,
                        on_change=lambda _: self._generate(), bg=PANEL_BG)
        row.pack(fill="x", padx=8, pady=7)
        return row

    def _mkbtn(self, parent, text, cmd, fg=DARK_FG, **pk):
        b = tk.Button(parent, text=text, command=cmd,
                      bg=BTN_BG, fg=fg, font=("Helvetica Neue", 11),
                      relief="flat", bd=0, padx=14, pady=7, cursor="hand2",
                      activebackground=BTN_ACTIVE, activeforeground=fg)
        b.pack(**pk)
        return b

    # ── build UI ──────────────────────────────────────────────────────────────

    def _build_ui(self):
        # ══════════════════════════════════════════════════════════════════════
        #  FIXED TOP AREA  (header + timeline + transport) — does NOT scroll
        # ══════════════════════════════════════════════════════════════════════
        top = tk.Frame(self, bg=DARK_BG)
        top.pack(fill="x", side="top")

        # Header
        hdr = tk.Frame(top, bg=DARK_BG)
        hdr.pack(fill="x", padx=16, pady=(14, 4))
        tk.Label(hdr, text="Comm Chirp Generator", bg=DARK_BG, fg=DARK_FG,
                 font=("Helvetica Neue", 17, "bold")).pack(side="left")
        tk.Label(hdr, text="FM Synthesis Engine", bg=DARK_BG, fg=MUTED,
                 font=("Helvetica", 10)).pack(side="left", padx=(10, 0), pady=(3, 0))

        # Timeline / waveform
        wf = tk.Frame(top, bg=DARK_BG)
        wf.pack(fill="x", padx=16, pady=(6, 0))
        self.wave_canvas = WaveCanvas(wf, on_change=self._on_timeline_drag)
        self.wave_canvas.pack(fill="x")
        tk.Label(wf, text="drag ▲ handles to reposition blips on the timeline",
                 bg=DARK_BG, fg=MUTED, font=("Helvetica", 9)).pack(anchor="e")

        # Transport row
        tr = tk.Frame(top, bg=DARK_BG)
        tr.pack(fill="x", padx=16, pady=8)
        self.play_btn = tk.Button(
            tr, text="▶  Play", command=self._play,
            bg=ACCENT, fg=DARK_BG, font=("Helvetica Neue", 13, "bold"),
            relief="flat", bd=0, padx=20, pady=8, cursor="hand2",
            activebackground="#74a7e8", activeforeground=DARK_BG)
        self.play_btn.pack(side="left", padx=(0, 8))
        self._mkbtn(tr, "⟳  Regenerate", self._generate, side="left", padx=(0, 8))
        self._mkbtn(tr, "💾  WAV", self._save_wav, fg=GREEN, side="left", padx=(0, 6))
        tk.Button(tr, text="💾  MP3", command=self._save_mp3,
                  bg=BTN_BG, fg=GREEN if HAS_PYDUB else MUTED,
                  font=("Helvetica Neue", 11), relief="flat", bd=0,
                  padx=14, pady=7, cursor="hand2", activebackground=BTN_ACTIVE,
                  state="normal" if HAS_PYDUB else "disabled").pack(side="left")
        self._mkbtn(tr, "💾  Arduino .h", self._save_arduino_h,
                    fg="#fab387", side="left", padx=(6, 0))
        if not HAS_PYDUB:
            tk.Label(tr, text="(pip install pydub)", bg=DARK_BG, fg=MUTED,
                     font=("Helvetica", 9)).pack(side="left", padx=6)

        # Thin divider line between fixed top and scrollable area
        tk.Frame(self, bg="#2e2e48", height=1).pack(fill="x", side="top")

        # Status bar — fixed at bottom
        self.status_var = tk.StringVar(value="Ready.")
        tk.Label(self, textvariable=self.status_var, bg=DARK_BG, fg=MUTED,
                 font=("Helvetica", 10), anchor="w"
                 ).pack(fill="x", side="bottom", padx=16, pady=(4, 8))
        tk.Frame(self, bg="#2e2e48", height=1).pack(fill="x", side="bottom")

        # ══════════════════════════════════════════════════════════════════════
        #  SCROLLABLE AREA  — sliders + presets
        # ══════════════════════════════════════════════════════════════════════
        sf = ScrollableFrame(self, bg=DARK_BG)
        sf.pack(fill="both", expand=True, side="top")
        sc = sf.inner   # all scrollable content goes here

        # ── Chirp shape ───────────────────────────────────────────────────────
        p1 = self._section(sc, "Chirp shape")

        style_row = tk.Frame(p1, bg=PANEL_BG)
        style_row.pack(fill="x", padx=8, pady=(8, 4))
        left_s = tk.Frame(style_row, bg=PANEL_BG, width=130)
        left_s.pack(side="left", fill="y"); left_s.pack_propagate(False)
        tk.Label(left_s, text="Chirp style", bg=PANEL_BG, fg=DARK_FG,
                 font=("Helvetica", 11), anchor="w").pack(fill="x")
        tk.Label(left_s, text="overall pattern shape", bg=PANEL_BG, fg=HINT_FG,
                 font=("Helvetica", 9), anchor="w").pack(fill="x")
        self.style_var = tk.StringVar(value="Rising sweep")
        cb = ttk.Combobox(style_row, textvariable=self.style_var,
                          values=[s[0] for s in STYLES],
                          state="readonly", width=17, font=("Helvetica", 11))
        cb.current(0); cb.pack(side="left", padx=(8, 0))
        cb.bind("<<ComboboxSelected>>", lambda e: self._on_style_change())

        self.s_dur = self._mkslider(p1, "Duration",
                                    "total length of the chirp",
                                    0.05, 0.60, 0.18, 0.01, " s", "{:.2f}")

        # ── Per-blip frequencies ──────────────────────────────────────────────
        pf = self._section(sc, "Blip frequencies")
        self.freq_panel = BlipFreqPanel(pf, on_change=self._generate)
        self.freq_panel.pack(fill="x")
        self.freq_panel.rebuild(1)

        # ── FM Texture ────────────────────────────────────────────────────────
        p2 = self._section(sc, "FM Texture")
        self.s_fma = self._mkslider(p2, "FM amount",
                                    "how much the tone wobbles / gets metallic",
                                    0, 400, 60, 5, "", "{:.0f}")
        self.s_fmr = self._mkslider(p2, "FM ratio",
                                    "pitch of the wobble relative to the tone",
                                    1.0, 8.0, 2.5, 0.5, "×", "{:.1f}")
        self.s_br  = self._mkslider(p2, "Brightness",
                                    "adds a higher harmonic — brighter, buzzier",
                                    0.0, 1.0, 0.5, 0.05, "", "{:.2f}")

        # ── Envelope ──────────────────────────────────────────────────────────
        p3 = self._section(sc, "Envelope")
        self.s_atk = self._mkslider(p3, "Attack",
                                    "how quickly the blip fades in from silence",
                                    0.001, 0.08, 0.006, 0.001, " s", "{:.3f}")
        self.s_rel = self._mkslider(p3, "Release",
                                    "how quickly the blip fades out to silence",
                                    0.01, 0.30, 0.08, 0.005, " s", "{:.3f}")
        self.s_vol = self._mkslider(p3, "Volume",
                                    "overall output level of the chirp",
                                    0.05, 1.00, 0.60, 0.05, "", "{:.2f}")

        # ── Presets ───────────────────────────────────────────────────────────
        p4  = self._section(sc, "Presets")
        row = tk.Frame(p4, bg=PANEL_BG)
        row.pack(fill="x", padx=8, pady=8)
        self._presets = [
            ("Classic",   dict(style="rise",   freqs=[(900,1400)],                       dur=0.18, fma=60,  fmr=2.5, br=0.50, atk=0.006, rel=0.08, vol=0.60)),
            ("Soft ping", dict(style="blip",   freqs=[(1200,700)],                       dur=0.14, fma=10,  fmr=2.0, br=0.15, atk=0.003, rel=0.10, vol=0.70)),
            ("Trill",     dict(style="trill",  freqs=[(800,1100),(900,1200),(1000,1300)], dur=0.28, fma=150, fmr=3.5, br=0.30, atk=0.005, rel=0.05, vol=0.65)),
            ("Deep comm", dict(style="fall",   freqs=[(800,500)],                        dur=0.25, fma=80,  fmr=1.5, br=0.60, atk=0.010, rel=0.12, vol=0.70)),
            ("Alien",     dict(style="double", freqs=[(1400,2200),(600,1800)],           dur=0.20, fma=320, fmr=5.0, br=0.80, atk=0.004, rel=0.07, vol=0.60)),
        ]
        for name, preset in self._presets:
            tk.Button(row, text=name,
                      command=lambda pp=preset: self._apply_preset(pp),
                      bg=BTN_BG, fg=ACCENT, font=("Helvetica Neue", 10),
                      relief="flat", bd=0, padx=10, pady=5,
                      cursor="hand2", activebackground=BTN_ACTIVE
                      ).pack(side="left", padx=(0, 6))

        tk.Frame(sc, bg=DARK_BG, height=12).pack()

    # ── style change ──────────────────────────────────────────────────────────

    def _on_style_change(self):
        style = next(k for l, k in STYLES if l == self.style_var.get())
        self.freq_panel.rebuild(n_blips_for_style(style), preserve=True)
        self._generate(reset_positions=True)

    # ── presets ───────────────────────────────────────────────────────────────

    def _apply_preset(self, p):
        lbl = next(l for l, k in STYLES if k == p["style"])
        self.style_var.set(lbl)
        self.freq_panel.rebuild(n_blips_for_style(p["style"]), preserve=False)
        self.freq_panel.set_freqs(p["freqs"])
        self.s_dur.set(p["dur"]); self.s_fma.set(p["fma"])
        self.s_fmr.set(p["fmr"]); self.s_br.set(p["br"])
        self.s_atk.set(p["atk"]); self.s_rel.set(p["rel"])
        self.s_vol.set(p["vol"])
        self._generate(reset_positions=True)

    # ── generate ──────────────────────────────────────────────────────────────

    def _generate(self, reset_positions=False):
        style    = next(k for l, k in STYLES if l == self.style_var.get())
        duration = self.s_dur.get()
        fm_amt   = self.s_fma.get()
        fm_ratio = self.s_fmr.get()
        bright   = self.s_br.get()
        attack   = self.s_atk.get()
        release  = self.s_rel.get()
        volume   = self.s_vol.get()

        default_segs = build_default_segments(style, duration)
        n_segs       = len(default_segs)
        freqs        = self.freq_panel.get_freqs()

        existing = self.wave_canvas.get_start_times()
        starts   = ([s for s, _ in default_segs]
                    if reset_positions or len(existing) != n_segs
                    else existing)

        audio_segs = []
        for i, (_, dur_s) in enumerate(default_segs):
            n      = int(dur_s * SAMPLE_RATE)
            sf, ef = freqs[i] if i < len(freqs) else (900, 1400)
            audio_segs.append(
                synth_segment(n, sf, ef, fm_amt, fm_ratio, bright, attack, release, volume)
            )

        self.wave_canvas.set_segments(
            list(zip(starts, [d for _, d in default_segs])), audio_segs)
        self._current_audio = self.wave_canvas.get_mixed_audio()
        dur_ms = int(len(self._current_audio) / SAMPLE_RATE * 1000)
        self.status_var.set(
            f"Generated — {n_segs} blip{'s' if n_segs>1 else ''}  ·  "
            f"{dur_ms} ms  ·  {SAMPLE_RATE} Hz  ·  16-bit mono"
        )

    def _on_timeline_drag(self):
        self._current_audio = self.wave_canvas.get_mixed_audio()
        starts = [f"{s*1000:.0f}" for s in self.wave_canvas.get_start_times()]
        dur_ms = int(len(self._current_audio) / SAMPLE_RATE * 1000)
        self.status_var.set(f"Positions: {', '.join(starts)} ms  ·  {dur_ms} ms total")

    # ── transport ─────────────────────────────────────────────────────────────

    def _play(self):
        if self._current_audio is None: self._generate()
        audio = self._current_audio.copy()
        def _do():
            try:    play_audio(audio)
            except Exception as e: self.status_var.set(f"Playback error: {e}")
        threading.Thread(target=_do, daemon=True).start()

    # ── export ────────────────────────────────────────────────────────────────

    def _save_wav(self):
        if self._current_audio is None: self._generate()
        path = filedialog.asksaveasfilename(
            defaultextension=".wav", filetypes=[("WAV audio", "*.wav")],
            initialfile="comm_chirp.wav")
        if not path: return
        try:
            save_wav(path, self._current_audio)
            self.status_var.set(f"Saved WAV → {os.path.basename(path)}")
        except Exception as e:
            messagebox.showerror("Save error", str(e))

    def _save_mp3(self):
        if self._current_audio is None: self._generate()
        path = filedialog.asksaveasfilename(
            defaultextension=".mp3", filetypes=[("MP3 audio", "*.mp3")],
            initialfile="comm_chirp.mp3")
        if not path: return
        try:
            save_mp3(path, self._current_audio)
            self.status_var.set(f"Saved MP3 → {os.path.basename(path)}")
        except Exception as e:
            messagebox.showerror("Save error", f"{e}\n\nMake sure ffmpeg is on your PATH.")

    def _save_arduino_h(self):
        if self._current_audio is None: self._generate()
        path = filedialog.asksaveasfilename(
            defaultextension=".h", filetypes=[("C header", "*.h")],
            initialfile="comm_chirp.h")
        if not path: return
        try:
            # Use the filename stem as the C variable name, sanitised
            stem = os.path.splitext(os.path.basename(path))[0]
            var  = "".join(c if c.isalnum() else "_" for c in stem).lstrip("0123456789") or "chirp"
            save_arduino_h(path, self._current_audio, var_name=var)
            n = len(self._current_audio)
            self.status_var.set(
                f"Saved Arduino .h → {os.path.basename(path)}  "
                f"({n} samples, 8-bit unsigned PCM)"
            )
        except Exception as e:
            messagebox.showerror("Save error", str(e))


# ═══════════════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    ChirpApp().mainloop()
